version: '3.5'

services:
  postgres:
    container_name: boilerplate_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
